// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShadowTraceAPI.Data;

#nullable disable

namespace ShadowTraceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626174216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShadowTraceAPI.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvestigationCaseId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationCaseId");

                    b.HasIndex("PerformedById");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.CaseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignmentReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvestigationCaseId")
                        .HasColumnType("integer");

                    b.Property<int>("InvestigatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationCaseId");

                    b.HasIndex("InvestigatorId");

                    b.ToTable("CaseAssignments");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.CaseSuspect", b =>
                {
                    b.Property<int>("InvestigationCaseId")
                        .HasColumnType("integer");

                    b.Property<int>("SuspectId")
                        .HasColumnType("integer");

                    b.HasKey("InvestigationCaseId", "SuspectId");

                    b.HasIndex("SuspectId");

                    b.ToTable("CaseSuspects");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvestigationCaseId")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationCaseId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.InvestigationCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InvestigationCases");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.Suspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Suspects");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.ActivityLog", b =>
                {
                    b.HasOne("ShadowTraceAPI.Entities.InvestigationCase", "InvestigationCase")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("InvestigationCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShadowTraceAPI.Entities.User", "PerformedBy")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigationCase");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.CaseAssignment", b =>
                {
                    b.HasOne("ShadowTraceAPI.Entities.InvestigationCase", "InvestigationCase")
                        .WithMany("CaseAssignments")
                        .HasForeignKey("InvestigationCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShadowTraceAPI.Entities.User", "Investigator")
                        .WithMany("CaseAssignments")
                        .HasForeignKey("InvestigatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigationCase");

                    b.Navigation("Investigator");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.CaseSuspect", b =>
                {
                    b.HasOne("ShadowTraceAPI.Entities.InvestigationCase", "InvestigationCase")
                        .WithMany("CaseSuspects")
                        .HasForeignKey("InvestigationCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShadowTraceAPI.Entities.Suspect", "Suspect")
                        .WithMany("CaseSuspects")
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigationCase");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.Evidence", b =>
                {
                    b.HasOne("ShadowTraceAPI.Entities.InvestigationCase", "InvestigationCase")
                        .WithMany("Evidence")
                        .HasForeignKey("InvestigationCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShadowTraceAPI.Entities.User", "UploadedBy")
                        .WithMany("UploadedEvidence")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestigationCase");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.InvestigationCase", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("CaseAssignments");

                    b.Navigation("CaseSuspects");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.Suspect", b =>
                {
                    b.Navigation("CaseSuspects");
                });

            modelBuilder.Entity("ShadowTraceAPI.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("CaseAssignments");

                    b.Navigation("UploadedEvidence");
                });
#pragma warning restore 612, 618
        }
    }
}
